GET http://localhost:3003/api/blogs
Authorization: Bearer 
###

GET http://localhost:3003/api/blogs/676756fec0a87bddf1605f76

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
  "title": "Fourth blog of Holyrus",
  "author": "Holyrus",
  "url": "https://examplelink.edu",
  "likes": 2027
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZlcm9uaWthIiwiaWQiOiI2NzdjNzNiODdiNTM2NzY2Njk2YTFkZTYiLCJpYXQiOjE3MzYyMDkzNzAsImV4cCI6MTczNjIxMjk3MH0.x82LlUUX0NY2RWJ4K70BC0YduszBbCqCnr_Cwcr_4YI

{
  "title": "Blog Vero",
  "author": "Veronika",
  "url": "https://examplelink.edu",
  "likes": 123
}

###
DELETE http://localhost:3003/api/blogs/67788ec78804f7fa03b26fdc
Authorization: Bearer 

###

PUT http://localhost:3003/api/blogs/676f71af97f7e515cdce462b
Content-Type: application/json

{
  "title": "Without likes",
  "author": "Me and Umka",
  "url": "https://examplelink.edu",
  "likes": 40
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Veronika",
  "name": "Vero",
  "password": "Umka1234"
}

###

DELETE http://localhost:3003/api/users/6778874f3c800b4f8bb00130
###