GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/676756fec0a87bddf1605f76

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhvbHlydXMiLCJpZCI6IjY3NzJmZmYzNTA1NDE1NTAwYTcxNDJjYiIsImlhdCI6MTczNTYwMDE4MCwiZXhwIjoxNzM1NjAzNzgwfQ.ACRNVaZzEV82dnn14pTGvBS0_0DiOpF_P-qYTNiVii4

{
  "title": "Second blog of Holyrus",
  "author": "Holyrus",
  "url": "https://examplelink.edu",
  "likes": 2026
}

###

DELETE http://localhost:3003/api/blogs/676883c3f7db5069fcadcb41

###

PUT http://localhost:3003/api/blogs/676f71af97f7e515cdce462b
Content-Type: application/json

{
  "title": "Without likes",
  "author": "Me and Umka",
  "url": "https://examplelink.edu",
  "likes": 40
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Popopopo",
  "name": "Fofffof",
  "password": "P23FFDF3"
}

###

DELETE http://localhost:3003/api/users/6771de30a275c4dd0a759c9c

###