GET http://localhost:3003/api/blogs
Authorization: Bearer 
###

GET http://localhost:3003/api/blogs/676756fec0a87bddf1605f76

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
  "title": "Fourth blog of Holyrus",
  "author": "Holyrus",
  "url": "https://examplelink.edu",
  "likes": 2027
}

###
DELETE http://localhost:3003/api/blogs/67788ec78804f7fa03b26fdc
Authorization: Bearer 

###

PUT http://localhost:3003/api/blogs/676f71af97f7e515cdce462b
Content-Type: application/json

{
  "title": "Without likes",
  "author": "Me and Umka",
  "url": "https://examplelink.edu",
  "likes": 40
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Popopopo",
  "name": "Fofffof",
  "password": "P23FFDF3"
}

###

DELETE http://localhost:3003/api/users/6778874f3c800b4f8bb00130
###